### ISSUE TITLE
Main method not found while running eotconverter

### ISSUE THREAD

**Issue by djrrb** [googlei18n/sfntly#49]
I've never used sfntly before so there's a good chance this is user error, but Dave Crossland thought someone here might be able to help. 

After a succesful ant build of sfntly, I tried the following:

> $ cd cd /Users/david/Documents/Tools/fontGenerate/sfntly
> $ java -jar java/dist/tools/conversion/eot/eotconverter.jar /Users/david/Desktop/test/Bungee-Regular.ttf

I get the error:

> Error: Main method not found in class com.google.typography.font.tools.conversion.eot.EOTWriter, please define the main method as:
> public static void main(String[] args)

Running in Terminal.app with Java 1.7.0_51 on Mac 10.10.3.

Thanks for whatever advice you may be able to give!

**Comment by anthrotype** [comment]
Hi David,
You can't use the eotconverter.jar directly from the command line. You need to use through the sfnttool.jar which is inside tools directory.
Cheers!

C.

**Comment by anthrotype** [comment]
this is the command to make an MTX-compressed EOT file: 
```bash
$ java -jar sfnttool.jar -e -x input.ttf output.eot
```

**Comment by anthrotype** [comment]
you might also be interested in a little Python wrapper for sfnttool.jar which I did some time ago:

https://github.com/daltonmaag/sfntly-py

It has a `convert` function which takes the format (can be either "eot" or "woff"), and the input file, and optionally the output file:

```python 
from sfntly import sfnttool
# save EOT in the same location of input font
sfnttool.convert('eot', 'font.ttf')

# save EOT to destination 'outfile'
sfnttool.convert('eot', 'font.ttf', outfile='font.eot')
```

It requires of course the Java runtime (it simply calls `java` as a subprocess, no fancy stuff here).
The setup.py script can compile sfnttool.jar from the java sources if you have the Java Development Kit and the `ant` tool installed.
Otherwise, ther are pre-compiled packages at `https://github.com/daltonmaag/sfntly-py/releases`, which you can pip install like this:

```
pip install --find-links https://github.com/daltonmaag/sfntly-py/releases sfntly
```

Cheers,

Cosimo

**Comment by djrrb** [comment]
Hi Cosimo,

Thanks so much for your quick and helpful responses! Using sfnttool.jar, I was able to generate EOTs without any issue.

Thanks also for letting me know about the python wrapper that you made. Sounds like something I can use in my scripts, and I will look into it further.

Again, thank you so much!
